### nginx.conf
server {
    listen 80;

    # Logs pour voir les erreurs (accessible via docker logs)
    error_log  /var/log/nginx/error.log warn;
    access_log /var/log/nginx/access.log;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

location /api/ {
        proxy_pass http://backend_service:80;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Servir les images uploadées (depuis le volume partagé)
    location /uploads/ {
        root /usr/share/nginx/html;
        try_files $uri =404;
        access_log off;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}